// Generated by tools/extract-vehicles.mjs — do not edit by hand.
// Paths are relative to the app's base URL, so the build works under a
// project-page subpath as well as at the domain root.
// dx/dy are offsets from the bay's axis-aligned box, in the same px
// units the isometric grid uses (74 px = one grid unit).

export interface SpriteMeta {
  file: string;
  dx: number;
  dy: number;
  w: number;
  h: number;
}

export const SPRITES: Record<string, SpriteMeta> = {
  'compact-f': {"file":"vehicles/compact-f.svg","dx":98.64,"dy":-17.83,"w":355.18,"h":296.99},
  'hatchback-f': {"file":"vehicles/hatchback-f.svg","dx":86.65,"dy":-27.86,"w":416.5,"h":321.05},
  'passenger-van-f': {"file":"vehicles/passenger-van-f.svg","dx":70.78,"dy":-82.11,"w":428.76,"h":390.27},
  'passenger-van-b': {"file":"vehicles/passenger-van-b.svg","dx":97.18,"dy":-35.26,"w":440.02,"h":332.95},
  'small-van-f': {"file":"vehicles/small-van-f.svg","dx":109.92,"dy":-75.2,"w":353.69,"h":353.44},
  'small-van-b': {"file":"vehicles/small-van-b.svg","dx":100.16,"dy":-61.12,"w":350.97,"h":340.04},
  'panel-van-f': {"file":"vehicles/panel-van-f.svg","dx":44.2,"dy":-142.29,"w":497.22,"h":456.31},
  'panel-van-b': {"file":"vehicles/panel-van-b.svg","dx":48.39,"dy":-90.84,"w":506.65,"h":402.74},
  'truck-f': {"file":"vehicles/truck-f.svg","dx":51.59,"dy":-120.84,"w":466.57,"h":416.34},
  'truck-b': {"file":"vehicles/truck-b.svg","dx":47.36,"dy":-158.49,"w":467.11,"h":451.15},
  'semi-tractor-f': {"file":"vehicles/semi-tractor-f.svg","dx":31.68,"dy":-111.84,"w":526.81,"h":431.17},
  'semi-tractor-b': {"file":"vehicles/semi-tractor-b.svg","dx":22.55,"dy":-138.84,"w":535.13,"h":457.72},
  'sedan-f': {"file":"vehicles/sedan-f.svg","dx":80.24,"dy":-16.84,"w":416.07,"h":314.85},
  'wagon-f': {"file":"vehicles/wagon-f.svg","dx":78.24,"dy":-33.84,"w":427,"h":337.61},
  'suv-f': {"file":"vehicles/suv-f.svg","dx":56.76,"dy":-63.95,"w":455.63,"h":369.9},
  'coach-f': {"file":"vehicles/coach-f.svg","dx":38.74,"dy":-190.34,"w":849.02,"h":702.2},
  'coach-b': {"file":"vehicles/coach-b.svg","dx":6.62,"dy":-154.69,"w":844.06,"h":685.77},
  'bus-f': {"file":"vehicles/bus-f.svg","dx":17.61,"dy":-204.17,"w":699.9,"h":602.14},
  'bus-b': {"file":"vehicles/bus-b.svg","dx":38.89,"dy":-195.22,"w":694.47,"h":610.78},
};

/** How far the tallest sprite reaches above its bay. */
export const MAX_OVERHANG = 205;
